const tailwindAt = ["tailwind", "apply", "variants", "responsive", "screen", "layer"]

module.exports = {
    extends: ["stylelint-config-recommended"],
    plugins: [
        "stylelint-order",
        "stylelint-scss"
    ],
    ignoreFiles: ["node_modules/**", "dist/**"],
    rules: {
        "at-rule-no-unknown": [
            true,
            {
                ignoreAtRules: tailwindAt
            }
        ],
        "scss/at-rule-no-unknown": [
            true,
            {
                ignoreAtRules: tailwindAt
            }
        ],
        "selector-max-id": null,
        "selector-class-pattern": null,
        "declaration-block-trailing-semicolon": null,
        "no-descending-specificity": null,
        "no-irregular-whitespace": null,
        "no-invalid-position-at-import-rule": null,
        "declaration-block-no-duplicate-custom-properties": null,
        "no-duplicate-selectors": null,
        "selector-pseudo-element-no-unknown": null,
        "order/properties-order": [
            "position",
            "top",
            "right",
            "bottom",
            "left",
            "z-index",
            "display",
            "float",
            "width",
            "height",
            "max-width",
            "max-height",
            "min-width",
            "min-height",
            "padding",
            "padding-top",
            "padding-right",
            "padding-bottom",
            "padding-left",
            "margin",
            "margin-top",
            "margin-right",
            "margin-bottom",
            "margin-left",
            "margin-collapse",
            "margin-top-collapse",
            "margin-right-collapse",
            "margin-bottom-collapse",
            "margin-left-collapse",
            "overflow",
            "overflow-x",
            "overflow-y",
            "clip",
            "clear",
            "font",
            "font-family",
            "font-size",
            "font-smoothing",
            "osx-font-smoothing",
            "font-style",
            "font-weight",
            "line-height",
            "letter-spacing",
            "word-spacing",
            "color",
            "text-align",
            "text-decoration",
            "text-indent",
            "text-overflow",
            "text-rendering",
            "text-size-adjust",
            "text-shadow",
            "text-transform",
            "word-break",
            "word-wrap",
            "white-space",
            "vertical-align",
            "list-style",
            "list-style-type",
            "list-style-position",
            "list-style-image",
            "pointer-events",
            "cursor",
            "background",
            "background-color",
            "border",
            "border-radius",
            "content",
            "outline",
            "outline-offset",
            "opacity",
            "filter",
            "visibility",
            "size",
            "transform"
        ]
    }
}
